---
name: learn-bosh

releases:
- name: learn-bosh
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  max_in_flight: 2
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
  - name: learn-bosh-app
    instances: 1
    azs: [z1]
    jobs:
    - name: app
      release: learn-bosh
      properties: {port: 8080}
    vm_type: default
    stemcell: default
    networks:
    - name: default
      static_ips: [10.193.64.241]
